import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch / Material Design 3 tokens (dark theme)
        "background": "#15121b",
        "surface": "#15121b",
        "surface-dim": "#15121b",
        "surface-bright": "#3b3742",
        "surface-container-lowest": "#0f0d15",
        "surface-container-low": "#1d1a23",
        "surface-container": "#211e27",
        "surface-container-high": "#2c2832",
        "surface-container-highest": "#37333d",
        "surface-variant": "#37333d",
        "on-background": "#e7e0ed",
        "on-surface": "#e7e0ed",
        "on-surface-variant": "#cbc3d7",
        "outline": "#958ea0",
        "outline-variant": "#494454",
        "primary": "#d0bcff",
        "on-primary": "#3c0091",
        "primary-container": "#a078ff",
        "on-primary-container": "#340080",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#d0bcff",
        "on-primary-fixed": "#23005c",
        "on-primary-fixed-variant": "#5516be",
        "inverse-primary": "#6d3bd7",
        "secondary": "#ffb0cd",
        "on-secondary": "#640039",
        "secondary-container": "#aa0266",
        "on-secondary-container": "#ffbad3",
        "secondary-fixed": "#ffd9e4",
        "secondary-fixed-dim": "#ffb0cd",
        "on-secondary-fixed": "#3e0022",
        "on-secondary-fixed-variant": "#8c0053",
        "tertiary": "#4cd7f6",
        "on-tertiary": "#003640",
        "tertiary-container": "#009eb9",
        "on-tertiary-container": "#002f38",
        "tertiary-fixed": "#acedff",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-tertiary-fixed": "#001f26",
        "on-tertiary-fixed-variant": "#004e5c",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e7e0ed",
        "inverse-on-surface": "#322f39",
        "surface-tint": "#d0bcff",
      },
      spacing: {
        "sidebar_width": "260px",
        "container_max": "1200px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        full: "0.75rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h3": ["18px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      animation: {
        "slide-in-right": "slideInRight 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
        "fade-in": "fadeIn 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
      },
      keyframes: {
        slideInRight: {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        fadeIn: {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
